Repository FFXIV-CombatReborn/RebornRotations, pull requests merged in 2024-07, with the labels that each got.

#77 Update SAM_Default.cs
  BasicRotations/Melee/SAM_Default.cs
Labels: bug, enhancement

#96 Added logic for 3 actions so usable at lower levels - Monk Rotation
  BasicRotations/Melee/MNK_Default.cs
Labels: under review

#131 Fixed Reign Combo
  BasicRotations/Tank/GNB_Default.cs
Labels: good first issue

#149 MNK full auto
  BasicRotations/Melee/MNK_Default.cs
Labels: under review

#160 Prioritize Perfectio so it fits into Arcane Circle window
  BasicRotations/Melee/RPR_Default.cs
Labels: enhancement, under review
